apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-proxy-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-proxy-admin-binding
subjects:
- kind: ServiceAccount
  name: helm-proxy-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-proxy
  namespace: default
  labels:
    app: helm-proxy
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helm-proxy
  template:
    metadata:
      labels:
        app: helm-proxy
        version: v1.0.0
    spec:
      serviceAccountName: helm-proxy-sa
      # Init 容器：初始化 Helm 仓库
      initContainers:
      - name: init-repo
        image: alpine/helm:3.12
        command: ["/bin/sh", "-c"]
        args: 
          - |
            # 初始化基础仓库（需要根据实际情况调整）
            helm repo add stable https://charts.helm.sh/stable --force-update || true
            helm repo add bitnami https://charts.bitnami.com/bitnami --force-update || true
            helm repo update
            cp -r /root/.config /data/ || true
            cp -r /root/.cache /data/ || true
        volumeMounts:
        - name: helm-data
          mountPath: /data
        - name: helm-cache
          mountPath: /root/.cache
        - name: helm-config
          mountPath: /root/.config
      containers:
      - name: helm-proxy
        image: helm-proxy:latest
        ports:
        - containerPort: 8443
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "8443"
        - name: GIN_MODE
          value: "release"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8443
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: helm-data
          mountPath: /root/.config
          subPath: config
        - name: helm-cache
          mountPath: /root/.cache
          subPath: cache
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: helm-data
        emptyDir: {}
      - name: helm-cache
        emptyDir: {}
      - name: helm-config
        emptyDir: {}
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: helm-proxy
  namespace: default
  labels:
    app: helm-proxy
spec:
  selector:
    app: helm-proxy
  ports:
  - name: http
    port: 8443
    targetPort: 8443
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helm-proxy
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
  - host: helm-proxy.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helm-proxy
            port:
              number: 8443